### ISSUE TITLE
Provide recommended/sample .gitignore

### ISSUE THREAD

**Issue by tschbc** [bcgov/BC-Policy-Framework-For-GitHub#77]
Like how there is a sample readme, code of conduct, and contributing file, is there any appetite for including a sample or recommended gitignore?

At a minimum I was envisioning a link to [github/gitignore](https://github.com/github/gitignore) and an in-line sample of a gitignore that excludes secrets by file type.

**Comment by tschbc** [comment]
@sheaphillips Are you able to comment?

**Comment by sheaphillips** [comment]
@tschbc We are moving towards using DevHub Templates for creating and maintaining repo compliance/good practice and these will include additional and up-to-date  files including .gitignore based on "flavour" of repo (more or less the applicable tech stack). 

We will be working to update and improve content / guidance in this repo. As we do this, we expect to  increasing the focus on aspects that are specific to the BC Gov context rather than providing general guidance on `git` / GitHub practices, as this is well covered by GitHub own docs and elsewhere.
